import Link from "next/link";
import { StatusBadge } from "@/components/ui/status-badge";

export default function HomePage() {
  return <main className="shell"><section className="hero"><p className="eyebrow">Pesquisa financeira auditável</p><h1>Antes de medir risco, é preciso tornar a evidência confiável.</h1><p className="lede">O SECC organiza trajetórias financeiras, fontes e lacunas em torno de eventos de reestruturação. Esta fundação demonstra a experiência e a governança — sem apresentar score, rating ou probabilidade de default.</p><div className="actions"><Link className="button" href="/empresas">Explorar empresas demo</Link><Link className="button secondary" href="/metodologia">Entender as limitações</Link></div></section>
    <section className="grid three" aria-label="Princípios do produto"><article className="card dark"><p className="eyebrow">01 · Proveniência</p><h2>A fonte permanece perto do dado.</h2><p>Cada evidência publicável carrega organização, referência, data e estado de validação.</p></article><article className="card"><p className="eyebrow">02 · Ausência</p><h2>Vazio não significa zero.</h2><p>Os estados distinguem o que não foi pesquisado, não existe, não se aplica ou ainda está em revisão.</p></article><article className="card"><p className="eyebrow">03 · Governança</p><h2>Aprovar não é publicar.</h2><p>Curadoria, sincronização com Excel e release pública são eventos separados.</p></article></section>
    <section className="section"><div><p className="eyebrow">Leitura correta dos dados</p><h2>Estados explícitos evitam falsas conclusões.</h2></div><div className="grid three"><div className="card"><StatusBadge status="available"/><p>Valor confirmado por fonte e revisão.</p></div><div className="card"><StatusBadge status="unavailable"/><p>Pesquisado e confirmado indisponível.</p></div><div className="card"><StatusBadge status="under_review"/><p>Coletado, mas ainda fora da release pública.</p></div></div></section>
    <section className="section card"><div className="split"><div><p className="eyebrow">Ambiente de curadoria</p><h2>O fluxo completo é demonstrável sem dados reais.</h2><p className="lede">Crie, revise, aprove e simule a sincronização usando somente registros fictícios.</p></div><Link className="button" href="/admin/revisoes">Abrir caixa de revisões</Link></div></section>
  </main>;
}
